### PR TITLE
Chore/add lint autoformat

### PR DESCRIPTION
**Pull request by GuillaumeDeconinck**
### Added
- `eslint` & `prettier` packages
- Plugins for interoperability between these 2
- Config files for eslint & prettier
- `.editorconfig` file (automatically [used by prettier apparently](https://prettier.io/docs/en/cli.html#--no-editorconfig))
- `husky` and `lint-staged` for precommit hooks
- Config files for Husky & lint-staged
  - Precommit hook that `prettier --write` && `npm run lint`

### Changed
- Added `lint` command to `package.json`
- Formatted **all** files in `lib`
- Formatted **all** JS files in `test`
- Formatted `bin` and `index.js`
- Auto-generated project has been updated with new dependencies (maybe it shouldn't be ?)

### Todos
- [x] Likely add the `lint` command to a workflow
- [x] Ideally lint/prettier as well the tests, so that the conventions are the same everywhere
- [x] Maybe add a pre-commit hook which run `prettier -w` on all the files

Linked to https://github.com/seriousme/fastify-openapi-glue/issues/370

### CODE REVIEW

**Comment by seriousme** [comment]
Thx :-)

Some questions:
- Can we change ` "es2020": true,` to `"es2021": true,`  or `"es2022": true,`  to reenable toplevel await in `generator.js`.
- I tried to lint/prettier the tests myself before but got all kinds of errors. Would be nice if that could be included as well ;-)

Precommit hook and addition of the lint step to CI sounds great as soon as got full coverage ;-)

Kind regards,
Hans

**Comment by GuillaumeDeconinck** [comment]
- Apparently we can indeed, I'll check tomorrow to move to `es2022` and see if we can revert the change on the toplevel await ;)
- Yes, that's definitely the next step, to have the lint on the tests as well

Nice, I'll try to check that as well after the two points mentioned above (and check why the CI fails) ;)

Btw, do not hesitate to edit/push on this MR is you want to add stuff or change something

Best regards

**Comment by seriousme** [comment]
Nice work !
Can we add `/index.js` and `/bin` as well ? ;-)

Kind regards,
Hans

**Comment by seriousme** [comment]
Btw: should we also do index.d.ts ?
Looks like we need a whole truck of additional dependencies for that :-(

Kind regards,
Hans

**Comment by GuillaumeDeconinck** [comment]
Thanks!
You're right, I didn't notice the `/bin` folder, it should be added too indeed, as well as the `index.js`, I'll check that :)
For `index.d.ts`, I'm not sure actually. Do you generate it in some way based on the JS or is it written by hand ?

Yes, unfortunately it adds a bunch of dependencies 😅 It's the price to pay for convenience, fortunately they are all well known packages. I'm not an expert (yet) in making public libraries, but I'm wondering if these packages shouldn't actually be in `optionalDependencies` or `peerDependencies`, to avoid these to be installed by default (no need to have a test framework or lint of the lib installed when actually using the lib inside an app). Do you have an idea ?

Best regards

**Comment by GuillaumeDeconinck** [comment]
Nevermind, `devDependencies` are apparently not installed when doing `npm install package_name`, only prod ([ref](https://stackoverflow.com/questions/18875674/whats-the-difference-between-dependencies-devdependencies-and-peerdependencies)). I learned something today :)

**Comment by GuillaumeDeconinck** [comment]
Totally understandable, I have the same stance on the production dependencies ;)

As you say, devDependencies are not that much of an issue (but still can be a liability for the devs of the lib. Hopefully, it won't happen. I suppose the added devDependencies here are fine/ok for you ?

Ok, I guess at some point they can/will be auto-generated in a precommit hook as well, but that's another story for another time. If it's rarely updated, I think it stay outside of the linting process then, except if you want to add them ;)

**Comment by GuillaumeDeconinck** [comment]
Thanks for the info, it would likely have taken me quite some time to understand the issue!

Ok perfect then for the time being :)

That would be nice! You made me think as well to rustfmt and rust's clippy (lint), the official "tools" of Rust. Node should definitely have the same kind of official tools indeed :/

**Comment by seriousme** [comment]
Thx !

**Pull request merged**
