### PR TITLE
Make initialize on Security Handlers async

### PR DESCRIPTION
**Pull request by AlexBroadbent**
Update `initialize(schemes)` to be `async initialize(schemes)` and await the result when setting up the service.

This means that users can perform an asynchronous task before the service starts.

### CODE REVIEW

**Comment by AlexBroadbent** [comment]
@seriousme I've hit a snag where I need to await the result of the initialize function, I've made the change to support it and updated the documentation.

**Comment by seriousme** [comment]
Thanks !

**Comment by AlexBroadbent** [comment]
@seriousme Could this be back-ported to `2.7.x`? I'm on an older version due as I can't upgrade to ESM yet, I've made the [changes against the tag, but I can't push a PR from my fork](https://github.com/seriousme/fastify-openapi-glue/compare/v2.7.2...AlexBroadbent:fastify-openapi-glue:async-security-hanlders-initialize?expand=1).

**Comment by seriousme** [comment]
The lastest 2.x is 2.7.2, are you ok if  backport it into 2.8.0 ?

Kind regards,
Hans

**Comment by AlexBroadbent** [comment]
Thanks @seriousme

**Comment by seriousme** [comment]
Backport is published as 2.8.0 on NPM

**Pull request merged**
