### PR TITLE
Enable security enforcement

### PR DESCRIPTION
**Pull request by mhamann**
Relates to:
- https://github.com/seriousme/fastify-openapi-glue/issues/51
- https://github.com/seriousme/fastify-openapi-glue/issues/43

I wanted a way to enforce one or more security requirements in a granular fashion. Most operations might require a certain (global) security mechanism, whereas others might use a different mechanism or even multiple.

Based on the issues and documentation, I couldn't figure out a way to do this cleanly, so. I put this together.

I still need to update the readme, but in a nutshell, it works like this:
- Define security schemes/definitions in OpenAPI/Swagger doc
- Define security requirements in OpenAPI doc, either globally, per operation, or both
- Write normal fastify "route" functions with the `(req, reply)` signature that implement the API's authentication requirements
- Pass a `securityHandlers` object as a property of the `fastify-openapi-glue` plugin initialization. The keys of this object should match those in the `security` requirements section of the OpenAPI document. The values are refs to the functions defined in the previous step.

The security handlers are attached as `preHandlers` to the appropriate operation routes. If any handler succeeds, the request proceeds normally. If all fail, the request is rejected.

### CODE REVIEW

**Comment by seriousme** [comment]
Hi,

nice idea to let the user decide which mechanism to be implemented and warn for unimplemented security mechanisms.

Few remarks:
- currently service.js exposes a class, it might be logical for security.js to expose a class as well so they both work in similar fashion,what do you think ?
- it would be nice if the generator would also generate a stub for security.js just like it does for service.js

Kind regards,
Hans

**Comment by mhamann** [comment]
Thanks for the feedback. I'll make those adjustments shortly and push them up.

**Comment by mhamann** [comment]
@seriousme sorry it took me so long to get back to this. PR updated to use a Security class (like Service) and I also built the module into the generator.

**Comment by seriousme** [comment]
Many thanks!
Hans

**Pull request merged**
